apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-authenticator
  namespace: cat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-authenticator
  template:
    metadata:
      labels:
        app: cat-authenticator
      annotations:
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: t3.medium
      containers:
      - name: cat-authenticator 
        image: ghcr.io/datakaveri/cat-prod:3.0-3a7684e
        resources:
          limits:
            cpu: 500m
            memory: 800Mi
          requests:
            cpu: 300m
            memory: 800Mi
        volumeMounts:
          - name: cat-config-authenticator
            mountPath: /usr/share/app/secrets/one-verticle-configs
        ports:
          - name: prometheus
            containerPort: 9000
            protocol: TCP
          - name: hazelcast
            containerPort: 5701
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
        envFrom:
          - configMapRef:
              name: cat-env
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        command: ["/bin/bash"]
        args: ["-c","exec java -Xmx1024m -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory  -jar ./fatjar.jar  --host $$MY_POD_IP -c secrets/one-verticle-configs/config-authenticator.json"]
      volumes:
        - name: cat-config-authenticator
          secret:
            secretName: cat-config-authenticator

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cat-authenticator
  namespace: cat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cat-authenticator
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

