version: "3.4"

networks:
  overlay-net:
    external: true
    driver: overlay

services:
  rs-nginx:
    image: dockerhub.iudx.io/iudx/nginx:1.20
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.rs_nginx_node==true"
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 10s
    ports:
      - target: 443
        published: 443
        mode: host
    secrets:
      - source: rs-key
        target: /etc/ssl/rs-key
      - source: rs-cert
        target: /etc/ssl/rs-cert
    configs:
      - source: rs-conf
        target: /etc/nginx/templates/nginx.conf.template
      - source: error-conf
        target: /etc/nginx/conf.d/error.conf
    networks:
      - overlay-net
    env_file:
      - ./.env

configs:
  rs-conf:
    file: conf/rs.conf
  error-conf:
    file: conf/error.conf
secrets:
  rs-key:
    file: secrets/rs-key
  rs-cert:
    file: secrets/rs-cert
